# Generated by Django 5.0.6 on 2024-06-25 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_skill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='total_experience',
        ),
        migrations.DeleteModel(
            name='EmployeeSkill',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
