# Generated by Django 5.0.6 on 2024-06-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skills', models.JSONField()),
                ('skill_levels', models.JSONField()),
                ('total_work_experience', models.IntegerField(help_text='Total years of work experience')),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
