# Generated by Django 5.0.6 on 2024-06-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_skill_level_skill_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(default='Beginner', max_length=100),
        ),
    ]
